# Generated by Django 4.2.11 on 2025-08-05 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('event', 'Event'), ('fast_start', 'Fast Started'), ('fast_join', 'Joined Fast'), ('fast_leave', 'Left Fast'), ('devotional_available', 'Devotional Available'), ('milestone', 'Milestone Reached'), ('fast_reminder', 'Fast Reminder'), ('devotional_reminder', 'Devotional Reminder')], help_text='Type of activity', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the target object', null=True)),
                ('title', models.CharField(help_text='Activity title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Activity description')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has seen this activity')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the user marked this as read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this activity was created')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data related to the activity')),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the target object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('event', models.ForeignKey(blank=True, help_text='Related event (if this is event-based)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='events.event')),
                ('user', models.ForeignKey(help_text='User who this activity is for', on_delete=django.db.models.deletion.CASCADE, related_name='activity_feed_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='events_user_user_id_bae739_idx'), models.Index(fields=['user', 'activity_type'], name='events_user_user_id_72e34a_idx'), models.Index(fields=['user', 'created_at'], name='events_user_user_id_b70b28_idx')],
            },
        ),
    ]
