# Generated by Django 4.2.11 on 2025-08-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_useractivityfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivityfeed',
            name='activity_type',
            field=models.CharField(choices=[('event', 'Event'), ('fast_start', 'Fast Started'), ('fast_join', 'Joined Fast'), ('fast_leave', 'Left Fast'), ('devotional_available', 'Devotional Available'), ('milestone', 'Milestone Reached'), ('fast_reminder', 'Fast Reminder'), ('devotional_reminder', 'Devotional Reminder'), ('user_registered', 'User Registered'), ('user_account_created', 'User Account Created'), ('article_published', 'Article Published'), ('recipe_published', 'Recipe Published'), ('video_published', 'Video Published')], help_text='Type of activity', max_length=50),
        ),
        migrations.AddIndex(
            model_name='useractivityfeed',
            index=models.Index(fields=['created_at', 'is_read'], name='events_user_created_715523_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivityfeed',
            index=models.Index(fields=['activity_type', 'created_at'], name='events_user_activit_a638a9_idx'),
        ),
    ]
