# Generated by Django 4.2.11 on 2025-08-10 20:02

from django.db import migrations


def create_user_account_created_event_type(apps, schema_editor):
    """Create EventType record for user account creation tracking."""
    EventType = apps.get_model('events', 'EventType')
    
    # Create the USER_ACCOUNT_CREATED event type if it doesn't exist
    user_account_created, created = EventType.objects.get_or_create(
        code='user_account_created',
        defaults={
            'name': 'User Account Created',
            'description': 'A user has completed account creation with profile setup',
            'category': 'user_action',
            'is_active': True,
            'requires_target': True,
        }
    )
    if created:
        print(f"Created EventType: {user_account_created.name}")


def reverse_create_user_account_created_event_type(apps, schema_editor):
    """Remove EventType record for user account creation tracking."""
    EventType = apps.get_model('events', 'EventType')
    
    # Remove the event type
    EventType.objects.filter(code='user_account_created').delete()
    print("Removed USER_ACCOUNT_CREATED EventType record")


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_user_account_created_event_type'),
    ]

    operations = [
        migrations.RunPython(
            create_user_account_created_event_type,
            reverse_create_user_account_created_event_type
        ),
    ]
