# Generated by Django 4.2.11 on 2025-08-10 19:50

from django.db import migrations


def create_user_account_event_types(apps, schema_editor):
    """Create EventType records for user account tracking."""
    EventType = apps.get_model('events', 'EventType')
    
    # Create the new event types if they don't exist
    user_registered, created = EventType.objects.get_or_create(
        code='user_registered',
        defaults={
            'name': 'User Registered',
            'description': 'A new user account has been registered',
            'category': 'user_action',
            'is_active': True,
            'requires_target': True,
        }
    )
    if created:
        print(f"Created EventType: {user_registered.name}")
    
    user_account_created, created = EventType.objects.get_or_create(
        code='user_account_created',
        defaults={
            'name': 'User Account Created',
            'description': 'A user has completed account creation with profile setup',
            'category': 'user_action',
            'is_active': True,
            'requires_target': True,
        }
    )
    if created:
        print(f"Created EventType: {user_account_created.name}")


def reverse_create_user_account_event_types(apps, schema_editor):
    """Remove EventType records for user account tracking."""
    EventType = apps.get_model('events', 'EventType')
    
    # Remove the event types
    EventType.objects.filter(code__in=['user_registered', 'user_account_created']).delete()
    print("Removed user account EventType records")


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_user_account_event_types'),
    ]

    operations = [
        migrations.RunPython(
            create_user_account_event_types,
            reverse_create_user_account_event_types
        ),
    ]
