# Generated by Django 4.2 on 2025-01-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_create_user_account_created_event_type_record'),
    ]

    operations = []
