# Generated by Django 4.2 on 2025-01-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_create_user_account_created_event_type_record'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX events_event_type_timestamp_idx ON events_event (event_type_id, timestamp DESC);",
            reverse_sql="DROP INDEX events_event_type_timestamp_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX events_content_type_object_timestamp_idx ON events_event (content_type_id, object_id, timestamp DESC);",
            reverse_sql="DROP INDEX events_content_type_object_timestamp_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX events_timestamp_date_idx ON events_event (date(timestamp));",
            reverse_sql="DROP INDEX events_timestamp_date_idx;"
        ),
    ]
