# Generated by Django 4.2.11 on 2025-08-29 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0005_add_analytics_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('first_fast_join', 'First Fast Joined'), ('first_nonweekly_fast_complete', 'First Non-Weekly Fast Completed')], help_text='Type of milestone achieved', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the related object', null=True)),
                ('achieved_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the milestone was achieved')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data related to the milestone (JSON format)')),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the related object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User who achieved the milestone', on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'milestone_type'], name='events_user_user_id_3d4f30_idx'), models.Index(fields=['achieved_at'], name='events_user_achieve_1716cb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='usermilestone',
            constraint=models.UniqueConstraint(fields=('user', 'milestone_type'), name='unique_user_milestone'),
        ),
    ]
