# Generated by Django 4.2.11 on 2025-08-29 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0031_alter_devotionalset_image'),
        ('events', '0006_usermilestone_usermilestone_unique_user_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivityfeed',
            name='activity_type',
            field=models.CharField(choices=[('event', 'Event'), ('fast_start', 'Fast Started'), ('fast_join', 'Joined Fast'), ('fast_leave', 'Left Fast'), ('devotional_available', 'Devotional Available'), ('milestone', 'Milestone Reached'), ('fast_reminder', 'Fast Reminder'), ('devotional_reminder', 'Devotional Reminder'), ('user_account_created', 'User Account Created'), ('article_published', 'Article Published'), ('recipe_published', 'Recipe Published'), ('video_published', 'Video Published'), ('announcement', 'Announcement')], help_text='Type of activity', max_length=50),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Announcement title', max_length=255)),
                ('description', models.TextField(help_text='Short description of the announcement')),
                ('url', models.URLField(blank=True, help_text='Optional URL for more information', max_length=2048)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publication status', max_length=20)),
                ('target_all_users', models.BooleanField(default=True, help_text='Send to all users')),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When to publish the announcement')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the announcement expires (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_recipients', models.PositiveIntegerField(default=0, help_text='Total number of users who received this announcement')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this announcement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_churches', models.ManyToManyField(blank=True, help_text='Send to specific churches (if not targeting all users)', to='hub.church')),
            ],
            options={
                'ordering': ['-publish_at'],
                'indexes': [models.Index(fields=['status', 'publish_at'], name='events_anno_status_74cf56_idx'), models.Index(fields=['expires_at'], name='events_anno_expires_7fe2ab_idx'), models.Index(fields=['target_all_users'], name='events_anno_target__0d0f83_idx')],
            },
        ),
    ]
