# Generated by Django 4.2.11 on 2025-10-02 03:20

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_make_checklist_used_target_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'description'), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='event',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'description'), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='useractivityfeed',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'description'), required_languages=(), virtual_fields=True),
        ),
    ]
