# Generated by Django 4.2.11 on 2025-09-27 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0034_alter_devotionalsettranslation_master_and_more'),
        ('events', '0009_remove_announcement_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='announcementtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='announcementtranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='useractivityfeedtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='useractivityfeedtranslation',
            name='master',
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_churches',
            field=models.ManyToManyField(blank=True, help_text='Send to specific churches (if not targeting all users)', to='hub.church'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='publish_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When to publish the announcement'),
        ),
        migrations.DeleteModel(
            name='AnnouncementTranslation',
        ),
        migrations.DeleteModel(
            name='UserActivityFeedTranslation',
        ),
    ]
