# Generated by Django 4.2.11 on 2025-11-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_add_screen_view_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermilestone',
            name='milestone_type',
            field=models.CharField(choices=[('first_fast_join', 'First Fast Joined'), ('first_nonweekly_fast_complete', 'First Non-Weekly Fast Completed'), ('first_prayer_request_created', 'First Prayer Request Created'), ('first_prayer_request_accepted', 'First Prayer Request Accepted'), ('prayer_warrior_10', 'Prayer Warrior - 10 Requests Accepted'), ('prayer_warrior_50', 'Prayer Warrior - 50 Requests Accepted'), ('faithful_intercessor', 'Faithful Intercessor - 7 Consecutive Days')], help_text='Type of milestone achieved', max_length=50),
        ),
    ]
