# Generated by Codex on 2026-05-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_add_tutorial_video_viewed_event_type'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS events_event_type_timestamp_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS events_content_type_object_timestamp_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
