# Generated by Django 4.2.11 on 2025-11-07 17:30

from django.db import migrations, models
import django.db.models.deletion
import icons.utils
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('hub', '0039_alter_llmprompt_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the icon', max_length=200)),
                ('image', models.ImageField(help_text='Main icon image. Recommended size: 1600x1200 pixels (4:3)', upload_to=icons.utils.icon_image_upload_path)),
                ('cached_thumbnail_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('cached_thumbnail_updated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(help_text='Church this icon belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='hub.church')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Tags for categorizing icons', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'Icons',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['church', 'created_at'], name='icons_icon_church__ed189b_idx')],
            },
        ),
    ]
