# Generated by Django 4.2.11 on 2026-03-23 05:02

from django.db import migrations, models
import icons.utils


class Migration(migrations.Migration):

    dependencies = [
        ("icons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="icon",
            name="image",
            field=models.ImageField(
                help_text="Main icon image. Thumbnail will be resized to fit within 400x300 preserving aspect ratio.",
                upload_to=icons.utils.icon_image_upload_path,
            ),
        ),
    ]
