# Generated by Django 5.2.14 on 2026-05-14 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icons", "0002_alter_icon_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="IconFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("mislabel", "Mislabeled"),
                            ("suggested_tags", "Suggest Tags"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(help_text="The actual feedback text")),
                (
                    "suggested_tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags, shown when type is suggested_tags",
                        max_length=500,
                    ),
                ),
                (
                    "submitter_email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional email for follow-up",
                        max_length=254,
                    ),
                ),
                (
                    "icon_title_at_time",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of icon title at submission time",
                        max_length=200,
                    ),
                ),
                (
                    "icon_tags_at_time",
                    models.TextField(
                        blank=True,
                        help_text="Snapshot of icon tags (comma-separated) at submission time",
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal admin notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("http_user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "icon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="icons.icon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Icon Feedback",
                "verbose_name_plural": "Icon Feedback",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["icon", "created_at"],
                        name="icons_iconf_icon_id_72208b_idx",
                    )
                ],
            },
        ),
    ]
