# Generated by Django 4.2.11 on 2026-05-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('icons', '0003_iconfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='icon',
            name='phash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
