# Generated by Django 5.2.17 on 2026-09-05 22:00

import django.db.models.deletion
import django.utils.timezone
import icons.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0064_fastintention_matched_tags_and_more'),
        ('icons', '0018_alter_iconfeedback_http_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('max_calls', models.PositiveIntegerField(default=0)),
                ('max_tokens', models.PositiveBigIntegerField(default=0)),
                ('max_microdollars', models.PositiveBigIntegerField(default=0)),
                ('calls', models.PositiveIntegerField(default=0)),
                ('tokens', models.PositiveBigIntegerField(default=0)),
                ('microdollars', models.PositiveBigIntegerField(default=0)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomyConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('subject', 'subject'), ('event', 'event'), ('group', 'group'), ('theme', 'theme')], max_length=16)),
                ('label', models.CharField(max_length=500)),
                ('definition', models.JSONField(default=dict)),
                ('source', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomyRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=80, unique=True)),
                ('source', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='icon',
            name='filename_provenance',
            field=models.CharField(default='unknown', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='icon',
            name='image_content_digest',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='icon',
            name='image_revision',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='icon',
            name='original_filename',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.ImageField(help_text='Main icon image. Descriptive original filenames are preserved as metadata claims, not visual proof. Thumbnail will be resized to fit within 400x300 preserving aspect ratio.', upload_to=icons.utils.icon_image_upload_path),
        ),
        migrations.CreateModel(
            name='IconObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('evidence', models.JSONField(default=dict)),
                ('state', models.CharField(default='pending', max_length=20)),
                ('lease_token', models.CharField(blank=True, max_length=36)),
                ('lease_until', models.DateTimeField(null=True)),
                ('returned_model', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.church')),
            ],
        ),
        migrations.CreateModel(
            name='IconAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64)),
                ('image_digest', models.CharField(max_length=64)),
                ('versions', models.JSONField(default=dict)),
                ('dependencies', models.JSONField(default=dict)),
                ('claims', models.JSONField(default=dict)),
                ('comparison', models.JSONField(default=dict)),
                ('state', models.CharField(default='pending', max_length=24)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('usage', models.JSONField(default=list)),
                ('error', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.church')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomic_analyses', to='icons.icon')),
                ('observation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='icons.iconobservation')),
            ],
        ),
        migrations.CreateModel(
            name='IconTaxonomyProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveBigIntegerField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('attributes', models.JSONField(default=list)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons.iconanalysis')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.church')),
                ('icon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_projection', to='icons.icon')),
            ],
        ),
        migrations.CreateModel(
            name='IconTaxonomyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('fingerprint', models.CharField(max_length=64)),
                ('state', models.CharField(db_index=True, default='pending', max_length=24)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(null=True)),
                ('lease_token', models.CharField(blank=True, max_length=36)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=80)),
                ('icon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_work', to='icons.icon')),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomyCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=20)),
                ('reserved_tokens', models.PositiveBigIntegerField()),
                ('reserved_microdollars', models.PositiveBigIntegerField()),
                ('usage', models.JSONField(null=True)),
                ('returned_model', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(default='reserved_unknown', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icons.iconanalysis')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='icons.taxonomybudget')),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomyAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='und', max_length=16)),
                ('text', models.CharField(max_length=500)),
                ('normalized', models.CharField(db_index=True, max_length=500)),
                ('source', models.JSONField(default=dict)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='icons.taxonomyconcept')),
            ],
        ),
        migrations.CreateModel(
            name='IconAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=16)),
                ('evidence_level', models.CharField(max_length=32)),
                ('rule', models.CharField(max_length=80)),
                ('evidence', models.JSONField(default=list)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='icons.iconanalysis')),
                ('concept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='icons.taxonomyconcept')),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('source', models.JSONField(default=dict)),
                ('source_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='icons.taxonomyconcept')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='icons.taxonomyconcept')),
            ],
        ),
        migrations.AddField(
            model_name='taxonomyconcept',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons.taxonomyrelease'),
        ),
        migrations.CreateModel(
            name='TaxonomyRequestInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.church')),
            ],
        ),
        migrations.AddConstraint(
            model_name='iconanalysis',
            constraint=models.UniqueConstraint(fields=('icon', 'digest'), name='icon_analysis_input'),
        ),
        migrations.AddConstraint(
            model_name='taxonomyalias',
            constraint=models.UniqueConstraint(fields=('concept', 'language', 'text'), name='taxonomy_alias_source'),
        ),
        migrations.AddIndex(
            model_name='iconassertion',
            index=models.Index(fields=['concept', 'status', 'evidence_level'], name='icons_icona_concept_a3e9eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxonomyrelation',
            constraint=models.UniqueConstraint(fields=('source_concept', 'target', 'kind'), name='taxonomy_relation_key'),
        ),
        migrations.AddConstraint(
            model_name='taxonomyconcept',
            constraint=models.UniqueConstraint(fields=('release', 'key'), name='taxonomy_concept_key'),
        ),
    ]
