"""The legacy bridge from a stored feast name to what the lectionary now calls that day.

``Feast`` rows were keyed by display text for years, across two sources that are both gone: the
retired sacredtradition.am scrape, and armenian-lectionary releases 1.1.x/1.2.x.  Display text is
the thing the engine corrects -- 1.3.0 folded ``Saint(s)`` to ``St(s).`` and fixed 122 component
spellings -- so a stored name drifts out of reach and takes its designation, icon and generated
contexts with it, silently.

``hub/data/feast_name_map.json`` is the one-time artifact that bridges those rows, generated by
``scripts/build_feast_name_map.py``.  Each entry records an old spelling, the name it resolved to
**and the date it resolved on**.  The date is the durable half: whatever an old source called a
day, asking the current engine about that same day still works, while the recorded target names
are a snapshot that goes stale with the next release.

This module is the artifact's reader plus the folding rule that makes a mangled stored name match
a clean one.  Nothing consumes it yet -- it is the data layer the re-key is built on.
"""
import datetime
import functools
import html
import json
import os
import unicodedata

import armenian_lectionary
from armenian_lectionary import MAX_YEAR, MIN_YEAR
NAME_MAP_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "feast_name_map.json"
)

# Armenian block (U+0530-U+058F) plus the Armenian ligatures in the Alphabetic Presentation
# Forms block (U+FB13-U+FB17), which is where "և" and friends can land.
_ARMENIAN_RANGES = ((0x0530, 0x058F), (0xFB13, 0xFB17))


def normalize_feast_key(name):
    """Fold a feast name to a key that survives how the scrape mangled it.

    Three separate kinds of damage have to collapse to the same key as the clean text:

      * **Jammed components.**  The source packs a position label, the commemoration and an eve
        note into one field separated by ``<br>``.  The retired scraper stripped every tag with no
        replacement, so a stored name reads ``"Eighth day of NativityFeast of Naming..."`` where
        the engine writes ``"Eighth day of Nativity — Feast of Naming..."``.
      * **Un-unescaped entities.**  The scraper never called ``html.unescape``.
      * **Cyrillic homoglyphs.**  The source occasionally types English feast text with Cyrillic
        ``Е``/``о``; the scraper preserved them.

    Dropping every character that is not Latin alphanumeric or Armenian handles all three at once
    -- separators and spacing vanish, and a homoglyph is dropped rather than folded.  That last
    one is only sound because the key is computed the same way on both sides: the map is keyed on
    ``normalize_feast_key(scraped_name)`` and looked up with ``normalize_feast_key(stored_name)``,
    and those are the same string.  Verified over all 429 names in the source corpus: no two
    distinct names collide on a key while disagreeing about the target.
    """
    if not name:
        return ""
    text = unicodedata.normalize("NFKC", html.unescape(name))
    kept = [ch for ch in text.lower() if _is_key_char(ch)]
    return "".join(kept)


def _is_key_char(ch):
    """True for Latin alphanumerics and Armenian letters; everything else is noise."""
    if ("a" <= ch <= "z") or ("0" <= ch <= "9"):
        return True
    point = ord(ch)
    return any(low <= point <= high for low, high in _ARMENIAN_RANGES)


@functools.lru_cache(maxsize=2)
def _names_by_date(language):
    """``{date: name}`` for the whole supported range, in one language.

    Cached: the sweep is a second of CPU and its result is fixed for a given engine version, so
    every caller in a process shares one.  ``feast_service`` keeps the inverse (name -> dates) for
    its own reasons; this direction is what a remap needs, to ask "what is this day called now".
    """
    names = {}
    day = datetime.date(MIN_YEAR, 1, 1)
    end = datetime.date(MAX_YEAR, 12, 31)
    while day <= end:
        result = armenian_lectionary.compute_armenian_lectionary(day, language=language)
        name = (result.get("Liturgical Day") or "").strip()
        if name:
            names[day] = name
        day += datetime.timedelta(days=1)
    return names


def engine_names(min_year=None, max_year=None):
    """Every distinct English name the engine emits -- the set a stored name must be in.

    A feast is looked up by the name the engine computes for the requested date, so a stored name
    outside this set is unreachable no matter what enrichment hangs off it.
    """
    min_year = MIN_YEAR if min_year is None else min_year
    max_year = MAX_YEAR if max_year is None else max_year
    return {
        name for day, name in _names_by_date("en").items()
        if min_year <= day.year <= max_year
    }


@functools.lru_cache(maxsize=1)
def load_name_map_entries():
    """Return the checked-in artifact's entries, each with its old spellings and current name.

    Missing file is not an error: the map only exists to bridge rows written before the ids, and
    a database that never held any (a fresh install, a test) needs nothing from it.
    """
    if not os.path.exists(NAME_MAP_PATH):
        return ()
    with open(NAME_MAP_PATH, encoding="utf-8") as fh:
        data = json.load(fh)
    return tuple(data.get("entries", ()))


@functools.lru_cache(maxsize=1)
def load_name_map():
    """Return ``{normalized old name: engine name at the time the map was built}``.

    Useful for reporting what a legacy row *was* called, but not for deciding what it is: these
    targets are display text from the engine version that generated the artifact, and 126 of the
    229 stopped being emitted verbatim at 2.0.0.  ``load_name_map_dates`` is the half that
    survives a release.
    """
    return {entry["key"]: entry["new"] for entry in load_name_map_entries()}


@functools.lru_cache(maxsize=1)
def load_name_map_dates():
    """Return ``{normalized old name: the date that name resolved to}``.

    This is the durable half of the artifact.  A date does not go stale: whatever an old source
    called a day, asking the *current* engine what that same day commemorates gives an answer
    that survives every rename since.  The ``new`` name beside it in the file was only ever the
    same question answered against the engine of the day, and answering it live is strictly
    better than trusting a snapshot.
    """
    dates = {}
    for entry in load_name_map_entries():
        raw = entry.get("sample_date")
        if raw:
            dates[entry["key"]] = datetime.date.fromisoformat(raw)
    return dates


