"""The legacy bridge from a stored feast name to what the lectionary now calls that day.

``Feast`` rows were keyed by display text for years, across two sources that are both gone: the
retired sacredtradition.am scrape, and armenian-lectionary releases 1.1.x/1.2.x.  Display text is
the thing the engine corrects -- 1.3.0 folded ``Saint(s)`` to ``St(s).`` and fixed 122 component
spellings -- so a stored name drifts out of reach and takes its designation, icon and generated
contexts with it, silently.

``hub/data/feast_name_map.json`` is the one-time artifact that bridges those rows, generated by
``scripts/build_feast_name_map.py`` against the engine the repo pins.  Each entry records an old
spelling, the name it resolved to **and the date it resolved on**.  The date is the durable half:
whatever an old source called a day, asking the current engine about that same day still works,
while the recorded target names are a snapshot that goes stale with the next release -- 138 of
the 244 entries carried over from the 1.3.0-targeted build changed their target name at 2.x, and
only 3 changed their date.

This module is the artifact's reader plus the folding rule that makes a mangled stored name match
a clean one.  Nothing consumes it yet -- it is the data layer the re-key is built on.  The reading
order a consumer owes it: match the stored name against ``engine_names()`` first and fall back to
``load_name_map_dates()`` only when that misses, because the fold can map a legacy spelling onto a
name the engine still emits.
"""
import datetime
import functools
import html
import json
import os
import types
import unicodedata

import armenian_lectionary
from armenian_lectionary import MAX_YEAR, MIN_YEAR

NAME_MAP_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "feast_name_map.json"
)

# Armenian block (U+0530-U+058F) plus the Armenian ligatures in the Alphabetic Presentation
# Forms block (U+FB13-U+FB17), which is where "և" and friends can land.
_ARMENIAN_RANGES = ((0x0530, 0x058F), (0xFB13, 0xFB17))


def normalize_feast_key(name):
    """Fold a feast name to a key that survives how the scrape mangled it.

    Three separate kinds of damage have to collapse to the same key as the clean text:

      * **Jammed components.**  The source packs a position label, the commemoration and an eve
        note into one field separated by ``<br>``.  The retired scraper stripped every tag with no
        replacement, so a stored name reads ``"Eighth day of NativityFeast of Naming..."`` where
        the engine writes ``"Eighth day of Nativity — Feast of Naming..."``.
      * **Un-unescaped entities.**  The scraper never called ``html.unescape``.
      * **Cyrillic homoglyphs.**  The source occasionally types English feast text with Cyrillic
        ``Е``/``о``; the scraper preserved them.

    Dropping every character that is not Latin alphanumeric or Armenian handles all three at once
    -- separators and spacing vanish, and a homoglyph is dropped rather than folded.  That last
    one is only sound because the key is computed the same way on both sides: the map is keyed on
    ``normalize_feast_key(scraped_name)`` and looked up with ``normalize_feast_key(stored_name)``,
    and those are the same string.  The fold is aggressive enough that a legacy key can equal a
    *current* name's key -- that is what happens when the only difference is a separator the fold
    erases -- so a caller must match the stored name against ``engine_names()`` first and consult
    the map only when that misses.  That no two distinct names collide on a key while disagreeing
    about the target is enforced twice: by ``assert_no_conflicting_keys`` when the artifact is
    generated, and by the test suite against the artifact that actually shipped.
    """
    if not name:
        return ""
    text = unicodedata.normalize("NFKC", html.unescape(name))
    kept = [ch for ch in text.lower() if _is_key_char(ch)]
    return "".join(kept)


def _is_key_char(ch):
    """True for Latin alphanumerics and Armenian letters; everything else is noise."""
    if ("a" <= ch <= "z") or ("0" <= ch <= "9"):
        return True
    point = ord(ch)
    return any(low <= point <= high for low, high in _ARMENIAN_RANGES)


@functools.lru_cache(maxsize=2)
def names_by_date(language="en"):
    """``{date: name}`` for the whole supported range, in one language.

    Public because ``scripts/build_feast_name_map.py`` builds the artifact against exactly this
    sweep.  A second, hand-synced copy of it there is how the generated keys would quietly stop
    describing the names the runtime compares against.

    Cached: the sweep is a second of CPU and its result is fixed for a given engine version, so
    every caller in a process shares one.  ``feast_service`` keeps the inverse (name -> dates) for
    its own reasons; this direction is what a remap needs, to ask "what is this day called now".
    """
    names = {}
    day = datetime.date(MIN_YEAR, 1, 1)
    end = datetime.date(MAX_YEAR, 12, 31)
    while day <= end:
        result = armenian_lectionary.compute_armenian_lectionary(day, language=language)
        name = (result.get("Liturgical Day") or "").strip()
        if name:
            names[day] = name
        day += datetime.timedelta(days=1)
    return names


def engine_names():
    """Every distinct English name the engine emits -- the set a stored name must be in.

    A feast is looked up by the name the engine computes for the requested date, so a stored name
    outside this set is unreachable no matter what enrichment hangs off it.  Deliberately the
    whole supported range and not a slice of it: a name is reachable if ANY date in range produces
    it, so narrowing the years would report reachable names as stranded.  A caller that wants one
    year's names is asking a different question and should filter ``names_by_date`` itself.
    """
    return set(names_by_date("en").values())


@functools.lru_cache(maxsize=1)
def load_name_map_entries():
    """Return the checked-in artifact's entries, each with its old spellings and the date it hit.

    Missing file is not an error: the map only exists to bridge rows written before the ids, and
    a database that never held any (a fresh install, a test) needs nothing from it.

    Entries come back read-only.  The result is cached for the process, so one caller editing an
    entry in place would hand every later caller the edit.
    """
    if not os.path.exists(NAME_MAP_PATH):
        return ()
    with open(NAME_MAP_PATH, encoding="utf-8") as fh:
        data = json.load(fh)
    return tuple(types.MappingProxyType(entry) for entry in data.get("entries", ()))


@functools.lru_cache(maxsize=1)
def load_name_map_dates():
    """Return ``{normalized old name: the date that name resolved to}``.

    The date is what the artifact is read for.  A date does not go stale: whatever an old source
    called a day, asking the *current* engine what that same day commemorates gives an answer
    that survives every rename since.  The ``new`` name recorded beside it is only the same
    question answered against the engine that generated the file, kept for provenance -- read it
    to report what a row *was* called, never to decide what it is now.
    """
    dates = {}
    for entry in load_name_map_entries():
        raw = entry.get("sample_date")
        if raw:
            dates[entry["key"]] = datetime.date.fromisoformat(raw)
    return dates


