# Generated by Django 4.2.11 on 2025-10-16 03:27

from django.db import migrations, models
import django.db.models.deletion
import modeltrans.fields
import prayers.utils
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hub', '0033_alter_devotional_unique_together_devotional_i18n_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(help_text='Main prayer content')),
                ('category', models.CharField(choices=[('morning', 'Morning Prayer'), ('evening', 'Evening Prayer'), ('meal', 'Meal Prayer'), ('general', 'General Prayer'), ('liturgical', 'Liturgical Prayer'), ('penitential', 'Penitential Prayer'), ('thanksgiving', 'Thanksgiving Prayer'), ('intercession', 'Intercession Prayer')], db_index=True, default='general', help_text='Category of prayer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('i18n', modeltrans.fields.TranslationField(fields=('title', 'text'), required_languages=(), virtual_fields=True)),
                ('church', models.ForeignKey(help_text='Church this prayer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prayers', to='hub.church')),
                ('fast', models.ForeignKey(blank=True, help_text='Optional fast association', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayers', to='hub.fast')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Tags for categorizing prayers', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Prayer',
                'verbose_name_plural': 'Prayers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, help_text='Description of the prayer set', null=True)),
                ('image', models.ImageField(blank=True, help_text='Image for the prayer set. Recommended size: 1600x1200 pixels (4:3)', null=True, upload_to=prayers.utils.prayer_set_image_upload_path)),
                ('cached_thumbnail_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('cached_thumbnail_updated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('i18n', modeltrans.fields.TranslationField(fields=('title', 'description'), required_languages=(), virtual_fields=True)),
                ('church', models.ForeignKey(help_text='Church this prayer set belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prayer_sets', to='hub.church')),
            ],
            options={
                'verbose_name': 'Prayer Set',
                'verbose_name_plural': 'Prayer Sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerSetMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of prayer within the set')),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='prayers.prayer')),
                ('prayer_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='prayers.prayerset')),
            ],
            options={
                'verbose_name': 'Prayer Set Membership',
                'verbose_name_plural': 'Prayer Set Memberships',
                'ordering': ['order'],
                'unique_together': {('prayer_set', 'prayer')},
            },
        ),
        migrations.AddField(
            model_name='prayerset',
            name='prayers',
            field=models.ManyToManyField(help_text='Prayers in this set', related_name='prayer_sets', through='prayers.PrayerSetMembership', to='prayers.prayer'),
        ),
        migrations.AddIndex(
            model_name='prayerset',
            index=models.Index(fields=['church', 'created_at'], name='prayers_pra_church__4204fa_idx'),
        ),
        migrations.AddIndex(
            model_name='prayer',
            index=models.Index(fields=['church', 'category'], name='prayers_pra_church__167ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='prayer',
            index=models.Index(fields=['church', 'fast'], name='prayers_pra_church__1ab116_idx'),
        ),
    ]
