# Generated by Django 4.2.11 on 2025-10-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerset',
            name='category',
            field=models.CharField(choices=[('morning', 'Morning Prayer'), ('evening', 'Evening Prayer'), ('general', 'General Prayer')], db_index=True, default='general', help_text='Category of prayer set', max_length=20),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='category',
            field=models.CharField(choices=[('morning', 'Morning Prayer'), ('evening', 'Evening Prayer'), ('general', 'General Prayer')], db_index=True, default='general', help_text='Category of prayer', max_length=20),
        ),
        migrations.AddIndex(
            model_name='prayerset',
            index=models.Index(fields=['church', 'category'], name='prayers_pra_church__f64de3_idx'),
        ),
    ]
