# Generated by Django 4.2.11 on 2025-11-18 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import prayers.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prayers', '0002_prayerset_category_alter_prayer_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title for the prayer request', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the prayer request')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide requester identity from users (visible to admins)')),
                ('duration_days', models.PositiveSmallIntegerField(choices=[(1, '1 day'), (2, '2 days'), (3, '3 days'), (4, '4 days'), (5, '5 days'), (6, '6 days'), (7, '7 days')], default=3, help_text='Duration of the prayer request (1-7 days)')),
                ('expiration_date', models.DateTimeField(db_index=True, help_text='Calculated expiration date based on creation + duration')),
                ('image', models.ImageField(blank=True, help_text='Optional image for the prayer request. Recommended size: 1600x1200 pixels (4:3)', null=True, upload_to=prayers.utils.prayer_request_image_upload_path)),
                ('cached_thumbnail_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('cached_thumbnail_updated', models.DateTimeField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False, help_text='Whether the request has been reviewed by moderation system')),
                ('status', models.CharField(choices=[('pending_moderation', 'Pending Moderation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('deleted', 'Deleted')], db_index=True, default='pending_moderation', help_text='Current status of the prayer request', max_length=20)),
                ('moderation_result', models.JSONField(blank=True, help_text='Results from LLM moderation process', null=True)),
                ('moderated_at', models.DateTimeField(blank=True, help_text='When the request was moderated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(help_text='User who submitted the prayer request', on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prayer Request',
                'verbose_name_plural': 'Prayer Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerRequestPrayerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayed_on_date', models.DateField(db_index=True, help_text='The date the user prayed for this request')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this log entry was created')),
                ('prayer_request', models.ForeignKey(help_text='The prayer request that was prayed for', on_delete=django.db.models.deletion.CASCADE, related_name='prayer_logs', to='prayers.prayerrequest')),
                ('user', models.ForeignKey(help_text='User who prayed', on_delete=django.db.models.deletion.CASCADE, related_name='prayer_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prayer Request Prayer Log',
                'verbose_name_plural': 'Prayer Request Prayer Logs',
                'ordering': ['-prayed_on_date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-prayed_on_date'], name='prayers_pra_user_id_a21206_idx'), models.Index(fields=['prayer_request', 'prayed_on_date'], name='prayers_pra_prayer__1b79d6_idx')],
                'unique_together': {('prayer_request', 'user', 'prayed_on_date')},
            },
        ),
        migrations.CreateModel(
            name='PrayerRequestAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, help_text='When the user accepted the prayer request')),
                ('prayer_request', models.ForeignKey(help_text='The prayer request that was accepted', on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='prayers.prayerrequest')),
                ('user', models.ForeignKey(help_text='User who accepted the prayer request', on_delete=django.db.models.deletion.CASCADE, related_name='accepted_prayer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prayer Request Acceptance',
                'verbose_name_plural': 'Prayer Request Acceptances',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', '-accepted_at'], name='prayers_pra_user_id_7c15ca_idx'), models.Index(fields=['prayer_request', '-accepted_at'], name='prayers_pra_prayer__d94a54_idx')],
                'unique_together': {('prayer_request', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['status', 'expiration_date'], name='prayers_pra_status_e93a76_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['requester', 'status'], name='prayers_pra_request_6f908d_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['reviewed', 'status'], name='prayers_pra_reviewe_b518ba_idx'),
        ),
    ]
