# Generated by Django 4.2.11 on 2025-11-18 22:10

from django.db import migrations, models
from django.db.models import F


def mark_self_acceptances(apps, schema_editor):
    """Mark existing self-acceptances so they don't count for milestones."""
    PrayerRequestAcceptance = apps.get_model('prayers', 'PrayerRequestAcceptance')
    PrayerRequestAcceptance.objects.filter(
        prayer_request__requester=F('user')
    ).update(counts_for_milestones=False)


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0003_prayerrequest_prayerrequestprayerlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequestacceptance',
            name='counts_for_milestones',
            field=models.BooleanField(default=True, help_text='Whether this acceptance should count toward milestone tracking'),
        ),
        migrations.RunPython(mark_self_acceptances, migrations.RunPython.noop),
    ]
