# Generated by Django 4.2.11 on 2025-11-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0004_prayerrequestacceptance_counts_for_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='moderation_severity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, help_text='Severity level from moderation', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='requires_human_review',
            field=models.BooleanField(db_index=True, default=False, help_text='Flagged for human review'),
        ),
    ]
