# Generated by Django 4.2.11 on 2025-12-26 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resources', '0008_article_i18n_recipe_i18n_video_i18n_and_more'),
        ('prayers', '0005_prayerrequest_moderation_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='video',
            field=models.ForeignKey(blank=True, help_text='Video containing audio recording of the prayer being read aloud and visuals integrated with the prayer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayers', to='learning_resources.video'),
        ),
    ]
