# Generated by Django 4.2.11 on 2026-01-03 01:59

from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0005_prayerrequest_moderation_severity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeastPrayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('Sundays, Dominical Feast Days', 'Sundays, Dominical Feast Days'), ('St. Gregory the Illuminator, St. Hripsime and her companions, the Apostles, the Prophets', 'St. Gregory the Illuminator, St. Hripsime and her companions, the Apostles, the Prophets'), ('Patriarchs, Vartapets', 'Patriarchs, Vartapets'), ('Nativity of Christ, Feasts of the Mother of God, Presentation of the Lord', 'Nativity of Christ, Feasts of the Mother of God, Presentation of the Lord'), ('Martyrs', 'Martyrs')], db_index=True, help_text='Feast designation this prayer is for', max_length=256, unique=True)),
                ('title', models.CharField(help_text='Prayer title template (can include {feast_name} placeholder)', max_length=200)),
                ('text', models.TextField(help_text='Prayer text template with {feast_name} placeholder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('i18n', modeltrans.fields.TranslationField(fields=('title', 'text'), required_languages=(), virtual_fields=True)),
            ],
            options={
                'verbose_name': 'Feast Prayer',
                'verbose_name_plural': 'Feast Prayers',
                'ordering': ['designation'],
            },
        ),
    ]
