# Generated by Django 4.2.11 on 2026-01-03 00:00

from django.db import migrations


class Migration(migrations.Migration):
    """
    Merge migration to resolve multiple leaf nodes:
    - 0006_feastprayer
    - 0006_prayer_video
    """

    dependencies = [
        ("prayers", "0006_feastprayer"),
        ("prayers", "0006_prayer_video"),
    ]

    operations = []


