# Generated by Django 4.2.11 on 2026-05-30 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("icons", "0003_iconfeedback"),
        ("prayers", "0008_prayerrequest_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayer",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prayers",
                to="icons.icon",
            ),
        ),
    ]
