# Generated by Django 4.2.11 on 2026-05-30 15:00

from django.db import migrations, models
import django.db.models.deletion
import prayers.utils


class Migration(migrations.Migration):
    dependencies = [
        ("icons", "0003_iconfeedback"),
        ("prayers", "0009_prayer_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayerset",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional fallback icon for this prayer set (used when no custom image is uploaded)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prayer_sets",
                to="icons.icon",
            ),
        ),
        migrations.AlterField(
            model_name="prayerset",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Custom image for the prayer set. Recommended size: 1600x1200 pixels (4:3)",
                null=True,
                upload_to=prayers.utils.prayer_set_image_upload_path,
            ),
        ),
    ]
