# Generated by Django 4.2.11 on 2024-05-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0001_initial_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="fast",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
