# Generated by Django 4.2.11 on 2024-05-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0002_fast_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="fast",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="fast_images/"),
        ),
    ]
