# Generated by Django 4.2.11 on 2024-05-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_day_date_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='fast',
            name='culmination_feast',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='fast',
            name='culmination_feast_date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
