# Generated by Django 4.2.11 on 2024-05-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_fast_add_culmination_feast_date_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='fast',
            constraint=models.UniqueConstraint(fields=('name', 'church'), name='unique_name_church'),
        ),
    ]
