# Generated by Django 4.2.11 on 2024-05-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0004_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
