# Generated by Django 4.2.11 on 2024-05-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_unique_date_unique_name_church_for_fast'),
    ]

    operations = [
        migrations.AddField(
            model_name='fast',
            name='url',
            field=models.URLField(blank=True, help_text='URL to a link to learn more--must include protocol (e.g. https://)', max_length=2048, null=True, verbose_name='Link to learn more'),
        ),
    ]
