# Generated by Django 4.2.11 on 2024-05-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_fast_culmination_feast_and_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fast',
            constraint=models.UniqueConstraint(fields=('name', 'church'), name='unique_name_church'),
        ),
    ]
