# Generated by Django 4.2.11 on 2024-05-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_fast_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fast',
            name='culmination_feast_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='fast',
            constraint=models.UniqueConstraint(fields=('culmination_feast_date', 'church'), name='unique_feast_date_church'),
        ),
    ]
