# Generated by Django 4.2.11 on 2024-05-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0007_unique_church_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
