# Generated by Django 4.2.11 on 2024-06-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0008_profile_location_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fast",
            name="culmination_feast_date",
            field=models.DateField(
                blank=True,
                help_text="You can enter in day/month/year format, e.g., 8/15/24",
                null=True,
            ),
        ),
    ]
