# Generated by Django 4.2.11 on 2024-07-21 03:52

from django.conf import settings
from django.apps import apps as global_apps
from django.db import migrations, models
import django.db.models.deletion


def get_default_church_pk():
    Church = global_apps.get_model('hub', 'Church')
    church, _ = Church.objects.get_or_create(name=settings.DEFAULT_CHURCH_NAME)
    return church.pk


def backfill_day_church(apps, schema_editor):
    Church = apps.get_model('hub', 'Church')
    Day = apps.get_model('hub', 'Day')
    church, _ = Church.objects.get_or_create(name=settings.DEFAULT_CHURCH_NAME)
    Day.objects.filter(church__isnull=True).update(church=church)


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_profile_receive_upcoming_fast_reminders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='_fast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.fast'),
        ),
        migrations.AddField(
            model_name='day',
            name='church',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='hub.church'),
        ),
        migrations.RunPython(
            backfill_day_church,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='day',
            name='church',
            field=models.ForeignKey(default=get_default_church_pk, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='hub.church'),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(),
        ),
    ]
