# Generated by Django 4.2.11 on 2024-07-21 03:52

from django.db import migrations, models
import django.db.models.deletion
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_profile_receive_upcoming_fast_reminders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='_fast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.fast'),
        ),
        migrations.AddField(
            model_name='day',
            name='church',
            field=models.ForeignKey(default=hub.models.Church.get_default_pk, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='hub.church'),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(),
        ),
    ]
