# Generated by Django 4.2.11 on 2024-07-21 03:53

from django.db import migrations


def save_fast_fk(apps, schema):
    Fast = apps.get_model('hub', 'Fast')
    Day = apps.get_model('hub', 'Day')
    for day in Day.objects.all():
        day._fast = day.fasts.all().first()
        day.save()


def save_fast_m2m(apps, schema):
    Fast = apps.get_model('hub', 'Fast')
    Day = apps.get_model('hub', 'Day')
    for day in Day.objects.all():
        if day._fast:
            day.fasts.add(day._fast)


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_day__fast_day_church_alter_day_date'),
    ]

    operations = [
        migrations.RunPython(save_fast_fk, save_fast_m2m)
    ]
