# Generated by Django 4.2.11 on 2024-07-21 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0014_rename__fast_day_fast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='fast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='hub.fast'),
        ),
    ]
