# Generated by Django 4.2.11 on 2024-11-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0017_unique_reading_per_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="include_weekly_fasts_in_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="receive_daily_fast_push_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="receive_ongoing_fast_push_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="receive_upcoming_fast_push_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
