# Generated by Django 4.2.11 on 2024-11-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0018_profile_include_weekly_fasts_in_notifications_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="include_weekly_fasts_in_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="receive_daily_fast_push_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="receive_upcoming_fast_reminders",
            field=models.BooleanField(default=False),
        ),
    ]
