# Generated by Django 4.2.11 on 2024-12-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0019_alter_profile_include_weekly_fasts_in_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, help_text='Name (first, last, whatever you want to be known as)', max_length=64, null=True),
        ),
    ]
