# Generated by Django 4.2.11 on 2025-02-22 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resources', '0001_initial'),
        ('hub', '0020_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevotionalSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Devotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, help_text='If part of a set, the order of the devotional in the set', null=True)),
                ('day', models.ForeignKey(help_text='Day for devotional (ensure that it belongs to proper church calendar)', on_delete=django.db.models.deletion.CASCADE, related_name='devotionals', to='hub.day')),
                ('devotional_set', models.ForeignKey(blank=True, help_text='Set that this devotional belongs to. If none, it is a standalone devotional.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devotionals', to='hub.devotionalset')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devotionals', to='learning_resources.video')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('devotional_set', 'order')},
            },
        ),
    ]
