# Generated by Django 4.2.11 on 2025-02-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0020_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fast',
            name='cached_thumbnail_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fast',
            name='cached_thumbnail_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cached_thumbnail_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cached_thumbnail_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
