# Generated by Django 4.2.11 on 2025-02-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0021_fast_cached_thumbnail_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cached_thumbnail_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cached_thumbnail_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
