# Generated by Django 4.2.11 on 2025-03-10 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0022_devotionalset_devotional'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastParticipantMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_file', models.FileField(blank=True, null=True, upload_to='fast_maps/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('participant_count', models.IntegerField(default=0)),
                ('format', models.CharField(default='svg', max_length=10)),
                ('fast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_maps', to='hub.fast')),
            ],
        ),
    ]
