# Generated by Django 4.2.11 on 2025-03-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0023_fastparticipantmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_text', models.CharField(db_index=True, max_length=255, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('error_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Geocoding Cache',
                'verbose_name_plural': 'Geocoding Cache',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
