# Generated by Django 4.2.11 on 2025-03-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0024_geocodingcache_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='day',
            index=models.Index(fields=['fast', 'date'], name='hub_day_fast_id_c4047f_idx'),
        ),
        migrations.AddIndex(
            model_name='day',
            index=models.Index(fields=['date'], name='hub_day_date_e1227f_idx'),
        ),
        migrations.AddIndex(
            model_name='day',
            index=models.Index(fields=['church', 'date'], name='hub_day_church__81dcf7_idx'),
        ),
        migrations.AddIndex(
            model_name='fast',
            index=models.Index(fields=['church'], name='hub_fast_church__4b1077_idx'),
        ),
        migrations.AddIndex(
            model_name='fastparticipantmap',
            index=models.Index(fields=['fast'], name='hub_fastpar_fast_id_38b986_idx'),
        ),
        migrations.AddIndex(
            model_name='fastparticipantmap',
            index=models.Index(fields=['last_updated'], name='hub_fastpar_last_up_47ed8b_idx'),
        ),
    ]
