# Generated by Django 4.2.11 on 2025-04-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0025_day_hub_day_fast_id_c4047f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receive_promotional_emails',
            field=models.BooleanField(default=True, help_text='Receive promotional emails'),
        ),
    ]
