# Generated by Django 4.2.11 on 2025-05-01 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0027_reading_context_reading_context_last_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('gpt-4.1-mini', 'GPT 4.1 Mini')], help_text='The LLM model used for generation', max_length=32)),
                ('role', models.TextField(help_text='The role/persona for the model')),
                ('prompt', models.TextField(help_text='The actual prompt text')),
                ('active', models.BooleanField(default=True, help_text='Whether the prompt is currently active')),
            ],
        ),
        migrations.RemoveField(
            model_name='reading',
            name='context',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='context_last_generated',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='context_thumbs_down',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='context_thumbs_up',
        ),
        migrations.CreateModel(
            name='ReadingContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The generated context text')),
                ('thumbs_up', models.PositiveIntegerField(default=0, help_text='Number of thumbs-up votes for the context')),
                ('thumbs_down', models.PositiveIntegerField(default=0, help_text='Number of thumbs-down votes for the context')),
                ('time_of_generation', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the context was generated', null=True)),
                ('active', models.BooleanField(default=True, help_text='Whether the context is currently active')),
                ('prompt', models.ForeignKey(blank=True, help_text='The prompt used to generate this context', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.llmprompt')),
                ('reading', models.ForeignKey(help_text='The reading this context is for', on_delete=django.db.models.deletion.CASCADE, related_name='reading_contexts', to='hub.reading')),
            ],
        ),
    ]
