# Generated by Django 4.2.11 on 2025-01-15 00:00

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import imagekit.processors
import model_utils.fields


def backfill_devotional_set_fast(apps, schema_editor):
    DevotionalSet = apps.get_model('hub', 'DevotionalSet')
    Devotional = apps.get_model('hub', 'Devotional')
    db_alias = schema_editor.connection.alias

    unresolved_set_ids = []
    ambiguous_sets = []

    for devotional_set in DevotionalSet.objects.using(db_alias).only('id'):
        fast_ids = list(
            Devotional.objects.using(db_alias)
            .filter(devotional_set_id=devotional_set.id)
            .values_list('day__fast_id', flat=True)
            .distinct()
        )

        if len(fast_ids) == 1 and fast_ids[0] is not None:
            DevotionalSet.objects.using(db_alias).filter(id=devotional_set.id).update(
                fast_id=fast_ids[0]
            )
        elif fast_ids:
            ambiguous_sets.append((devotional_set.id, fast_ids))
        else:
            unresolved_set_ids.append(devotional_set.id)

    if unresolved_set_ids or ambiguous_sets:
        raise ValueError(
            'Cannot infer DevotionalSet.fast for unresolved devotional sets '
            f'{unresolved_set_ids} or ambiguous devotional sets {ambiguous_sets}.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0028_llmprompt_remove_reading_context_and_more'),
    ]

    operations = [
        # First, remove the unique_together constraint that includes devotional_set
        migrations.AlterUniqueTogether(
            name='devotional',
            unique_together=set(),
        ),
        # Add new fields to DevotionalSet
        migrations.AddField(
            model_name='devotionalset',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the devotional set', null=True),
        ),
        migrations.AddField(
            model_name='devotionalset',
            name='fast',
            field=models.ForeignKey(help_text='The fast this devotional set is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devotional_sets', to='hub.fast'),
            preserve_default=False,
        ),
        migrations.RunPython(
            backfill_devotional_set_fast,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='devotionalset',
            name='fast',
            field=models.ForeignKey(help_text='The fast this devotional set is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='devotional_sets', to='hub.fast'),
        ),
        migrations.AddField(
            model_name='devotionalset',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the devotional set. Recommended size: 1600x1200 pixels (4:3)', null=True, upload_to='devotional_sets/'),
        ),
        migrations.AddField(
            model_name='devotionalset',
            name='cached_thumbnail_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='devotionalset',
            name='cached_thumbnail_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devotionalset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='devotionalset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        # Now remove devotional_set field from Devotional
        migrations.RemoveField(
            model_name='devotional',
            name='devotional_set',
        ),
        # Update help text for order field in Devotional
        migrations.AlterField(
            model_name='devotional',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Order of the devotional within the fast', null=True),
        ),
        # Update Meta options for both models
        migrations.AlterModelOptions(
            name='devotionalset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='devotional',
            options={'ordering': ['day__date', 'order']},
        ),
        # Add the new unique_together constraint on Devotional
        migrations.AlterUniqueTogether(
            name='devotional',
            unique_together={('day', 'order')},
        ),
    ]
