# Generated by Django 4.2.11 on 2025-01-15 00:00

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import imagekit.processors
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0028_llmprompt_remove_reading_context_and_more'),
    ]

    operations = [
        # First, remove the unique_together constraint that includes devotional_set
        migrations.AlterUniqueTogether(
            name='devotional',
            unique_together=set(),
        ),
        # Add new fields to DevotionalSet
        migrations.AddField(
            model_name='devotionalset',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the devotional set', null=True),
        ),
        migrations.AddField(
            model_name='devotionalset',
            name='fast',
            field=models.ForeignKey(default=1, help_text='The fast this devotional set is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='devotional_sets', to='hub.fast'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devotionalset',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the devotional set. Recommended size: 1600x1200 pixels (4:3)', null=True, upload_to='devotional_sets/'),
        ),
        migrations.AddField(
            model_name='devotionalset',
            name='cached_thumbnail_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='devotionalset',
            name='cached_thumbnail_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devotionalset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='devotionalset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        # Now remove devotional_set field from Devotional
        migrations.RemoveField(
            model_name='devotional',
            name='devotional_set',
        ),
        # Update help text for order field in Devotional
        migrations.AlterField(
            model_name='devotional',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Order of the devotional within the fast', null=True),
        ),
        # Update Meta options for both models
        migrations.AlterModelOptions(
            name='devotionalset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='devotional',
            options={'ordering': ['day__date', 'order']},
        ),
        # Add the new unique_together constraint on Devotional
        migrations.AlterUniqueTogether(
            name='devotional',
            unique_together={('day', 'order')},
        ),
    ]