# Generated by Django 4.2.11 on 2025-07-16 00:03

from django.db import migrations, models
import learning_resources.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0030_add_timezone_to_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotionalset',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the devotional set. Recommended size: 1600x1200 pixels (4:3)', null=True, upload_to=learning_resources.utils.devotional_set_image_upload_path),
        ),
    ]
