# Generated by Django 4.2.11 on 2025-10-02 03:20

from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0032_profile_utm_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devotional',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='devotional',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('description',), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='devotional',
            name='language_code',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='devotionalset',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'description'), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='fast',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'description', 'culmination_feast'), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterUniqueTogether(
            name='devotional',
            unique_together={('day', 'order', 'language_code')},
        ),
    ]
