# Generated by Django 4.2.11 on 2025-09-27 08:22

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0032_profile_utm_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevotionalSetTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, help_text='Description of the devotional set', null=True)),
            ],
            options={
                'verbose_name': 'devotional set Translation',
                'db_table': 'hub_devotionalset_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DevotionalTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'devotional Translation',
                'db_table': 'hub_devotional_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FastTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('culmination_feast', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'fast Translation',
                'db_table': 'hub_fast_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='fast',
            name='unique_name_church_year',
        ),
        migrations.AlterUniqueTogether(
            name='devotional',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='devotionalset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='devotionalset',
            name='title',
        ),
        migrations.RemoveField(
            model_name='fast',
            name='culmination_feast',
        ),
        migrations.RemoveField(
            model_name='fast',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fast',
            name='name',
        ),
        migrations.AddField(
            model_name='devotional',
            name='language_code',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='devotional',
            unique_together={('day', 'order', 'language_code')},
        ),
        migrations.AddField(
            model_name='fasttranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='hub.fast'),
        ),
        migrations.AddField(
            model_name='devotionaltranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='hub.devotional'),
        ),
        migrations.AddField(
            model_name='devotionalsettranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='hub.devotionalset'),
        ),
        migrations.RemoveField(
            model_name='devotional',
            name='description',
        ),
        migrations.AlterUniqueTogether(
            name='fasttranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='devotionaltranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='devotionalsettranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
