# Generated by Django 4.2.11 on 2025-10-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0033_add_culmination_feast_date_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='fast',
            name='culmination_feast_message',
            field=models.TextField(blank=True, help_text='Message for the culmination feast', null=True),
        ),
        migrations.AddField(
            model_name='fast',
            name='culmination_feast_message_attribution',
            field=models.CharField(blank=True, help_text='Attribution or author of the culmination feast message', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='fast',
            name='culmination_feast_salutation',
            field=models.CharField(blank=True, help_text='Greeting or salutation for the culmination feast', max_length=256, null=True),
        ),
    ]
