# Generated by Django 4.2.11 on 2025-10-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0033_alter_devotional_unique_together_devotional_i18n_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fast',
            index=models.Index(fields=['culmination_feast_date'], name='hub_fast_culmina_4b0578_idx'),
        ),
    ]
