# Generated by Django 4.2.11 on 2025-09-27 20:56

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0033_devotionalsettranslation_devotionaltranslation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotionalsettranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='hub.devotionalset'),
        ),
        migrations.AlterField(
            model_name='devotionaltranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='hub.devotional'),
        ),
        migrations.AlterField(
            model_name='fasttranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='hub.fast'),
        ),
    ]
