# Generated by Django 4.2.11 on 2025-10-06 22:36

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0035_add_culmination_feast_message_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fast',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'description', 'culmination_feast', 'culmination_feast_salutation', 'culmination_feast_message', 'culmination_feast_message_attribution'), required_languages=(), virtual_fields=True),
        ),
    ]
