# Generated by Django 4.2.11 on 2025-10-21 04:07

from django.db import migrations, models
import modeltrans.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('hub', '0036_update_fast_i18n_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatristicQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Quote text in Markdown format')),
                ('attribution', models.CharField(help_text="Source or author of the quote (e.g., 'St. John Chrysostom', 'The Desert Fathers')", max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('i18n', modeltrans.fields.TranslationField(fields=('text', 'attribution'), required_languages=(), virtual_fields=True)),
                ('churches', models.ManyToManyField(help_text='Churches this quote belongs to', related_name='patristic_quotes', to='hub.church')),
                ('fasts', models.ManyToManyField(blank=True, help_text='Optional fasts this quote is associated with', related_name='patristic_quotes', to='hub.fast')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Tags for categorizing quotes (e.g., prayer, fasting, humility)', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Patristic Quote',
                'verbose_name_plural': 'Patristic Quotes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='hub_patrist_created_b9bec3_idx'), models.Index(fields=['attribution'], name='hub_patrist_attribu_4440d5_idx')],
            },
        ),
    ]
