# Generated by Django 4.2.11 on 2025-11-03 21:30

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0037_patristicquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('book',), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='readingcontext',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('text',), required_languages=(), virtual_fields=True),
        ),
    ]
