# Generated by Django 4.2.11 on 2025-11-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0038_add_translation_fields_to_reading_and_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprompt',
            name='model',
            field=models.CharField(choices=[('gpt-4.1-mini', 'GPT 4.1 Mini'), ('gpt-4.1-nano', 'GPT 4.1 Nano'), ('gpt-4.1', 'GPT 4.1'), ('gpt-o4-mini', 'GPT o4 Mini (Reasoning $$$)'), ('gpt-4o-mini', 'GPT 4o Mini'), ('claude-haiku-4-5-20251001', 'Claude Haiku 4.5'), ('claude-sonnet-4-5-20250929', 'Claude Sonnet 4.5'), ('claude-3-7-sonnet-20250219', 'Claude 3.7 Sonnet'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet')], help_text='The LLM model used for generation', max_length=32),
        ),
    ]
