# Generated by Django 4.2.11 on 2025-11-06 13:53

from django.db import migrations, models
import django.db.models.deletion
import hub.models
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0039_alter_llmprompt_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date of the feast')),
                ('name', models.CharField(help_text='The name of the feast', max_length=256)),
                ('i18n', modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True)),
                ('church', models.ForeignKey(default=hub.models.Church.get_default_pk, help_text='The church this feast belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='feasts', to='hub.church')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='llmprompt',
            name='applies_to',
            field=models.CharField(choices=[('readings', 'Readings'), ('feasts', 'Feasts')], default='readings', help_text='What model this prompt applies to (readings or feasts)', max_length=16),
        ),
        migrations.CreateModel(
            name='FeastContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The generated context text')),
                ('short_text', models.TextField(blank=True, help_text='A shorter version of the context text', null=True)),
                ('thumbs_up', models.PositiveIntegerField(default=0, help_text='Number of thumbs-up votes for the context')),
                ('thumbs_down', models.PositiveIntegerField(default=0, help_text='Number of thumbs-down votes for the context')),
                ('time_of_generation', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the context was generated', null=True)),
                ('active', models.BooleanField(default=True, help_text='Whether the context is currently active')),
                ('i18n', modeltrans.fields.TranslationField(fields=('text', 'short_text'), required_languages=(), virtual_fields=True)),
                ('feast', models.ForeignKey(help_text='The feast this context is for', on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='hub.feast')),
                ('prompt', models.ForeignKey(blank=True, help_text='The prompt used to generate this context', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.llmprompt')),
            ],
        ),
        migrations.AddIndex(
            model_name='feast',
            index=models.Index(fields=['date', 'church'], name='hub_feast_date_f72277_idx'),
        ),
        migrations.AddIndex(
            model_name='feast',
            index=models.Index(fields=['date'], name='hub_feast_date_a26a83_idx'),
        ),
        migrations.AddConstraint(
            model_name='feast',
            constraint=models.UniqueConstraint(fields=('date', 'church'), name='unique_feast_per_date_church'),
        ),
    ]
