# Generated by Django 4.2.11 on 2025-11-06

from django.db import migrations, models
import django.db.models.deletion
import hub.models
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0039_alter_llmprompt_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=256)),
                ('i18n', modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True)),
                ('church', models.ForeignKey(default=hub.models.Church.get_default_pk, on_delete=django.db.models.deletion.CASCADE, related_name='feasts', to='hub.church')),
            ],
            options={
                'indexes': [models.Index(fields=['church', 'date'], name='hub_feast_church_date_idx'), models.Index(fields=['date'], name='hub_feast_date_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='feast',
            constraint=models.UniqueConstraint(fields=('date', 'church'), name='unique_feast_per_day_church'),
        ),
    ]
