# Generated by Django 4.2.11 on 2025-11-06 14:44

from django.db import migrations, models
import django.db.models.deletion
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0039_alter_llmprompt_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('i18n', modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feasts', to='hub.day')),
            ],
        ),
        migrations.AddField(
            model_name='llmprompt',
            name='applies_to',
            field=models.CharField(choices=[('readings', 'Readings'), ('feasts', 'Feasts')], default='readings', help_text='The type of content this prompt is used for', max_length=32),
        ),
        migrations.CreateModel(
            name='FeastContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The generated context text (longer format)')),
                ('short_text', models.TextField(help_text='The generated short context text (2 sentence summary)')),
                ('thumbs_up', models.PositiveIntegerField(default=0, help_text='Number of thumbs-up votes for the context')),
                ('thumbs_down', models.PositiveIntegerField(default=0, help_text='Number of thumbs-down votes for the context')),
                ('time_of_generation', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the context was generated', null=True)),
                ('active', models.BooleanField(default=True, help_text='Whether the context is currently active')),
                ('i18n', modeltrans.fields.TranslationField(fields=('text', 'short_text'), required_languages=(), virtual_fields=True)),
                ('feast', models.ForeignKey(help_text='The feast this context is for', on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='hub.feast')),
                ('prompt', models.ForeignKey(blank=True, help_text='The prompt used to generate this context', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.llmprompt')),
            ],
        ),
        migrations.AddConstraint(
            model_name='feast',
            constraint=models.UniqueConstraint(fields=('day',), name='unique_feast_per_day'),
        ),
    ]
