# Generated by Django 4.2.11 on 2025-11-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0040_add_feast_models_and_llmprompt_applies_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='feast',
            name='designation',
            field=models.CharField(blank=True, choices=[('Sundays, Dominical Feast Days', 'Sundays, Dominical Feast Days'), ('St. Gregory the Illuminator, St. Hripsime and her companions, the Apostles, the Prophets', 'St. Gregory the Illuminator, St. Hripsime and her companions, the Apostles, the Prophets'), ('Patriarchs, Vartapets', 'Patriarchs, Vartapets'), ('Nativity of Christ, Feasts of the Mother of God, Presentation of the Lord', 'Nativity of Christ, Feasts of the Mother of God, Presentation of the Lord'), ('Martyrs', 'Martyrs')], help_text='Classification of the feast, automatically determined by AI', max_length=256, null=True),
        ),
    ]
