# Generated by Django 4.2.11 on 2025-11-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0042_feast_icon_alter_llmprompt_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprompt',
            name='applies_to',
            field=models.CharField(choices=[('readings', 'Readings'), ('feasts', 'Feasts'), ('prayer_requests', 'Prayer Requests')], default='readings', help_text='The type of content this prompt is used for', max_length=32),
        ),
    ]
