# Generated by Django 4.2.11 on 2026-01-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0043_alter_llmprompt_applies_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receive_weekly_prayer_request_push_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
