# Generated by Django 4.2.11 on 2026-02-11 16:59

from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0044_add_weekly_prayer_request_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="reading",
            name="text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Verse content retrieved from API.Bible",
            ),
        ),
        migrations.AddField(
            model_name="reading",
            name="text_copyright",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Copyright notice from API.Bible for the retrieved text",
            ),
        ),
        migrations.AddField(
            model_name="reading",
            name="text_fetched_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the text was last fetched from API.Bible",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reading",
            name="text_version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Bible version used (e.g. NKJV, KJVAIC)",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="reading",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("book", "text"), required_languages=(), virtual_fields=True
            ),
        ),
    ]
