# Generated by Django 4.2.11 on 2026-02-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0045_reading_text_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="reading",
            name="fums_token",
            field=models.TextField(
                blank=True,
                default="",
                help_text="FUMS v3 token from API.Bible for fair-use tracking",
            ),
        ),
    ]
