# Generated by Django 4.2.11 on 2026-02-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0046_add_fums_token_to_reading"),
    ]

    operations = [
        migrations.AddField(
            model_name="reading",
            name="text_hy_copyright",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Copyright notice for the Armenian text",
            ),
        ),
        migrations.AddField(
            model_name="reading",
            name="text_hy_fetched_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the Armenian text was last fetched from sacredtradition.am",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reading",
            name="text_hy_fums_token",
            field=models.TextField(
                blank=True,
                default="",
                help_text="FUMS token for Armenian text (reserved for future use)",
            ),
        ),
        migrations.AddField(
            model_name="reading",
            name="text_hy_version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Armenian Bible version used (e.g. Նոր Էջմիածին)",
                max_length=64,
            ),
        ),
    ]
