# Generated by Django 4.2.11 on 2026-02-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0047_reading_text_hy_copyright_reading_text_hy_fetched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fast',
            name='has_day_zero',
            field=models.BooleanField(default=False, help_text='If True, the fast starts counting from Day 0 instead of Day 1'),
        ),
        migrations.AlterField(
            model_name='devotional',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Only matters when multiple devotionals exist on the same day. Controls display order and must be unique per day and language.', null=True),
        ),
    ]
