# Generated by Django 4.2.11 on 2026-03-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0048_add_start_day_number_to_fast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprompt',
            name='model',
            field=models.CharField(
                choices=[
                    ('o4-mini', 'o4 Mini'),
                    ('gpt-4.1-mini', 'GPT 4.1 Mini'),
                    ('gpt-4.1-nano', 'GPT 4.1 Nano'),
                    ('gpt-4o-mini', 'GPT 4o Mini'),
                    ('gpt-4.1', 'GPT 4.1'),
                    ('gpt-5-mini', 'GPT 5 Mini'),
                    ('gpt-5-nano', 'GPT 5 Nano'),
                    ('gpt-5-mini-2025-08-07', 'GPT 5 Mini (2025-08-07)'),
                    ('gpt-5', 'GPT 5'),
                    ('claude-haiku-4-5-20251001', 'Claude Haiku 4.5'),
                    ('claude-sonnet-4-6', 'Claude Sonnet 4.6'),
                    ('claude-sonnet-4-5-20250929', 'Claude Sonnet 4.5'),
                    ('claude-3-7-sonnet-20250219', 'Claude 3.7 Sonnet'),
                    ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'),
                ],
                help_text='The LLM model used for generation',
                max_length=32,
            ),
        ),
    ]
