# Generated by Django 4.2.11 on 2026-05-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0050_add_fast_designation_to_feast"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE hub_fast "
                "ADD COLUMN IF NOT EXISTS has_day_zero boolean NOT NULL DEFAULT false;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
