# Generated by Django 4.2.11 on 2026-05-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0050_add_fast_designation_to_feast"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="day",
            unique_together={("date", "church")},
        ),
    ]
