# Generated by Codex on 2026-05-29

from django.db import migrations


def disable_existing_weekly_prayer_request_push_opt_ins(apps, schema_editor):
    Profile = apps.get_model('hub', 'Profile')
    Profile.objects.update(receive_weekly_prayer_request_push_notifications=False)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0052_remove_unique_feast_per_day'),
    ]

    operations = [
        migrations.RunPython(
            disable_existing_weekly_prayer_request_push_opt_ins,
            reverse_code=noop_reverse,
        ),
    ]
