# Generated by Django 4.2.11 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0053_disable_weekly_prayer_request_push_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='Նոր Էջմիածին', help_text="Translation identifier, e.g. 'Նոր Էջմիածին' (Eastern Armenian).", max_length=32)),
                ('book', models.CharField(help_text="USFM book id, e.g. 'GEN', '1CO' (see hub.constants.BOOK_NAME_TO_USFM). The corpus is a superset of that map: a few unread deuterocanonical books (e.g. '1ES', '3MA') have no BOOK_NAME_TO_USFM entry.", max_length=3)),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField(help_text='Verse number; 0 denotes a chapter superscription/title.')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Bible Verse',
                'verbose_name_plural': 'Bible Verses',
                'ordering': ['version', 'book', 'chapter', 'verse'],
            },
        ),
        migrations.AddConstraint(
            model_name='bibleverse',
            constraint=models.UniqueConstraint(fields=('version', 'book', 'chapter', 'verse'), name='unique_bible_verse'),
        ),
    ]
