# Generated by Django 4.2.11 on 2026-07-22 15:14

from django.db import migrations, models
import django.db.models.deletion
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0054_bibleverse'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fastintention',
            new_name='hub_fastint_fast_id_e180ae_idx',
            old_name='hub_fastint_fast_id_7f8e1e_idx',
        ),
        migrations.RenameIndex(
            model_name='fastintention',
            new_name='hub_fastint_user_id_26dff9_idx',
            old_name='hub_fastint_user_id_3a2b1c_idx',
        ),
        migrations.AlterField(
            model_name='day',
            name='church',
            field=models.ForeignKey(default=hub.models.Church.get_default_pk, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='hub.church'),
        ),
    ]
