# Generated by Django 4.2.11 on 2026-07-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0055_sync_day_church_and_fastintention_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['day__date', 'sequence', 'id']},
        ),
        migrations.AddField(
            model_name='reading',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, help_text="Position of this reading within its day's list, as returned by the armenian_lectionary engine. Determines display order.", null=True),
        ),
    ]
