# Generated by Django 4.2.11 on 2026-07-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0056_alter_reading_options_reading_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='passage_key',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, help_text="Passage identity, e.g. 'GEN.1.1-1.5'. Readings sharing this key share one fetched text per language. Empty when the book name has no USFM mapping, i.e. when no retrieval is possible.", max_length=64),
        ),
        migrations.CreateModel(
            name='PassageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_key', models.CharField(db_index=True, help_text="Passage identity from hub.constants.passage_key, e.g. 'GEN.1.1-1.5'.", max_length=64)),
                ('language', models.CharField(help_text="ISO 639-1 code, e.g. 'en', 'hy'.", max_length=8)),
                ('text', models.TextField(blank=True, default='')),
                ('version', models.CharField(blank=True, default='', help_text="Edition the text came from, e.g. 'NKJV', 'KJVAIC', 'Նոր Էջմիածին'. A column rather than part of the key because it varies within a language: English uses NKJV for canonical books and KJVAIC for the Apocrypha.", max_length=64)),
                ('copyright', models.TextField(blank=True, default='', help_text='Copyright notice, stored exactly as the source returned it.')),
                ('fums_token', models.TextField(blank=True, default='', help_text='API.Bible FUMS v3 token, where the source issues one.')),
                ('fetched_at', models.DateTimeField(blank=True, help_text='When the text was retrieved. NULL means the passage is known but has never been fetched — how the warm-up enumerates work for the refresh task.', null=True)),
            ],
            options={
                'verbose_name': 'Passage Text',
                'verbose_name_plural': 'Passage Texts',
                'indexes': [models.Index(fields=['language', 'fetched_at'], name='passage_text_lang_fresh_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='passagetext',
            constraint=models.UniqueConstraint(fields=('passage_key', 'language'), name='unique_passage_text_per_language'),
        ),
    ]
