# Generated by Django 4.2.11 on 2026-07-27 05:41

from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0057_backfill_passage_keys_and_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='fums_token',
            field=models.TextField(blank=True, default='', help_text='LEGACY, unused -- text now lives in PassageText.'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('book',), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='text',
            field=models.TextField(blank=True, default='', help_text='LEGACY, unused -- text now lives in PassageText.'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='text_copyright',
            field=models.TextField(blank=True, default='', help_text='LEGACY, unused -- text now lives in PassageText.'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='text_fetched_at',
            field=models.DateTimeField(blank=True, help_text='LEGACY, unused -- text now lives in PassageText.', null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='text_hy_copyright',
            field=models.TextField(blank=True, default='', help_text='LEGACY, unused -- text now lives in PassageText.'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='text_hy_fetched_at',
            field=models.DateTimeField(blank=True, help_text='LEGACY, unused -- text now lives in PassageText.', null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='text_hy_fums_token',
            field=models.TextField(blank=True, default='', help_text='LEGACY, unused -- text now lives in PassageText.'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='text_hy_version',
            field=models.CharField(blank=True, default='', help_text='LEGACY, unused -- text now lives in PassageText.', max_length=64),
        ),
        migrations.AlterField(
            model_name='reading',
            name='text_version',
            field=models.CharField(blank=True, default='', help_text='LEGACY, unused -- text now lives in PassageText.', max_length=16),
        ),
    ]
