# Generated by Django 4.2.11 on 2026-08-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0063_finalize_feast_rekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastintention',
            name='matched_tags',
            field=models.JSONField(blank=True, default=None, help_text='LLM-derived prayer tags for this intention; null until computed', null=True),
        ),
        migrations.AlterField(
            model_name='llmprompt',
            name='applies_to',
            field=models.CharField(choices=[('readings', 'Readings'), ('feasts', 'Feasts'), ('prayer_requests', 'Prayer Requests'), ('intentions', 'Intentions')], default='readings', help_text='The type of content this prompt is used for', max_length=32),
        ),
    ]
