# Generated by Django 5.2.17 on 2026-09-17 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0069_feast_context_version_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="FastParticipation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "joined_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC timestamp of the join.  NULL when the period is recorded from a leave event with no prior join.",
                        null=True,
                    ),
                ),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC timestamp of the leave.  NULL while the period is still open.",
                        null=True,
                    ),
                ),
                (
                    "fast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="participations", to="hub.fast"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fast_participations",
                        to="hub.profile",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["fast", "left_at"], name="hub_fastpar_fast_id_4a65e5_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("left_at__isnull", True)),
                        fields=("profile", "fast"),
                        name="unique_open_fast_participation",
                    )
                ],
            },
        ),
    ]
