# Generated by Django 5.2.17 on 2026-09-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0069_feast_context_version_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmprompt",
            name="model",
            field=models.CharField(
                choices=[
                    ("o4-mini", "o4 Mini"),
                    ("gpt-4o-mini", "GPT 4o Mini"),
                    ("gpt-5-mini", "GPT 5 Mini"),
                    ("gpt-5-nano", "GPT 5 Nano"),
                    ("gpt-5-mini-2025-08-07", "GPT 5 Mini (2025-08-07)"),
                    ("gpt-5", "GPT 5"),
                    ("claude-haiku-4-5-20251001", "Claude Haiku 4.5"),
                    ("claude-sonnet-4-6", "Claude Sonnet 4.6"),
                    ("claude-sonnet-4-5-20250929", "Claude Sonnet 4.5"),
                    ("claude-3-5-sonnet-20241022", "Claude 3.5 Sonnet"),
                ],
                help_text="The LLM model used for generation",
                max_length=32,
            ),
        ),
    ]
