# Generated by Django 5.2.17 on 2026-09-17 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0070_alter_llmprompt_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="FastParticipation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "joined_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC join timestamp; NULL means unknown.",
                        null=True,
                    ),
                ),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC leave timestamp; NULL when open or unknown.",
                        null=True,
                    ),
                ),
                (
                    "ended_at_unknown",
                    models.BooleanField(
                        default=False,
                        db_default=False,
                        help_text="Membership ended but its leave timestamp is unknown.",
                    ),
                ),
                ("fast_original_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("fast_name", models.CharField(blank=True, default="", db_default="", max_length=128)),
                ("fast_year", models.IntegerField(blank=True, null=True)),
                ("fast_end_date", models.DateField(blank=True, null=True)),
                ("fast_deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fast",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participations",
                        to="hub.fast",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fast_participations",
                        to="hub.profile",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["fast", "left_at"], name="hub_fastpar_fast_id_4a65e5_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(left_at__isnull=True, ended_at_unknown=False),
                        fields=("profile", "fast"),
                        name="unique_open_fast_participation",
                    )
                ],
            },
        ),
    ]
