# Generated by Django 5.2.17 on 2026-10-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0071_backfill_fastparticipation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmprompt",
            name="model",
            field=models.CharField(
                choices=[
                    ("claude-sonnet-5-5", "Claude Sonnet 5.5"),
                    ("claude-haiku-5-5", "Claude Haiku 5.5"),
                    ("claude-sonnet-4-6", "Claude Sonnet 4.6"),
                    ("claude-haiku-4-5-20251001", "Claude Haiku 4.5"),
                    ("gpt-5.6-sol", "GPT 5.6 Sol"),
                    ("gpt-5.6-terra", "GPT 5.6 Terra"),
                    ("gpt-5.6-luna", "GPT 5.6 Luna"),
                    ("gpt-4o-mini", "GPT 4o Mini"),
                    ("claude-sonnet-4-5-20250929", "Claude Sonnet 4.5 (deprecated)"),
                    ("claude-3-5-sonnet-20241022", "Claude 3.5 Sonnet (retired)"),
                    ("o4-mini", "o4 Mini (deprecated)"),
                    ("gpt-5", "GPT 5 (deprecated)"),
                    ("gpt-5-mini", "GPT 5 Mini (deprecated)"),
                    ("gpt-5-nano", "GPT 5 Nano (deprecated)"),
                    ("gpt-5-mini-2025-08-07", "GPT 5 Mini 2025-08-07 (deprecated)"),
                ],
                help_text="The LLM model used for generation",
                max_length=32,
            ),
        ),
    ]
