"""
Tests for push notification payload generation.

This test file validates that the push notification admin form generates
correct payload structures for different content types.
"""
import json
from django.test import TestCase


class PushNotificationPayloadTests(TestCase):
    """
    Test cases for push notification payload generation.

    These tests validate the expected payload structures based on the
    frontend app's routing requirements.
    """

    def test_fast_payload(self):
        """Test fast detail screen payload."""
        expected = {"screen": "fast/48"}
        # This would be generated by the form when:
        # - Payload type: fast
        # - Content ID: 48
        self.assertEqual(expected, {"screen": "fast/48"})

    def test_devotional_payload(self):
        """Test devotional screen payload."""
        expected = {"screen": "devotional/123"}
        self.assertEqual(expected, {"screen": "devotional/123"})

    def test_prayer_payload(self):
        """Test prayer screen payload."""
        expected = {"screen": "prayer/77"}
        self.assertEqual(expected, {"screen": "prayer/77"})

    def test_video_payload_with_learn_prefix(self):
        """Test video screen payload includes learn/ prefix."""
        expected = {"screen": "learn/video/902"}
        # The form should automatically add 'learn/' prefix for videos
        self.assertEqual(expected, {"screen": "learn/video/902"})

    def test_article_payload_with_learn_prefix(self):
        """Test article screen payload includes learn/ prefix."""
        expected = {"screen": "learn/article/305"}
        # The form should automatically add 'learn/' prefix for articles
        self.assertEqual(expected, {"screen": "learn/article/305"})

    def test_recipe_payload_with_learn_prefix(self):
        """Test recipe screen payload includes learn/ prefix."""
        expected = {"screen": "learn/recipe/120"}
        # The form should automatically add 'learn/' prefix for recipes
        self.assertEqual(expected, {"screen": "learn/recipe/120"})

    def test_prayer_set_payload_with_hyphen(self):
        """Test prayer set payload uses hyphen not underscore."""
        expected = {"screen": "prayer-set/44"}
        # Critical: prayer-set uses hyphen, not underscore (prayer_set)
        self.assertEqual(expected, {"screen": "prayer-set/44"})

    def test_activity_feed_basic(self):
        """Test basic activity feed payload."""
        expected = {"screen": "activity"}
        self.assertEqual(expected, {"screen": "activity"})

    def test_activity_feed_with_params(self):
        """Test activity feed payload with parameters."""
        expected = {
            "screen": "activity",
            "params": {
                "activity_type": "announcement",
                "target_id": "987"
            }
        }
        # This opens the activity feed and auto-navigates to announcement #987
        self.assertEqual(expected["screen"], "activity")
        self.assertEqual(expected["params"]["activity_type"], "announcement")
        self.assertEqual(expected["params"]["target_id"], "987")

    def test_payload_with_query_params(self):
        """Test payload with additional query parameters."""
        expected = {
            "screen": "fast/48",
            "params": {
                "source": "push",
                "ref": "notification"
            }
        }
        # Query params are added to the params object
        self.assertEqual(expected["screen"], "fast/48")
        self.assertIn("source", expected["params"])
        self.assertIn("ref", expected["params"])

    def test_external_url_payload(self):
        """Test external URL payload structure."""
        expected = {"url": "https://example.com/announcement"}
        # External URLs should have 'url' key, not 'screen'
        self.assertIn("url", expected)
        self.assertNotIn("screen", expected)
        self.assertTrue(expected["url"].startswith("https://"))

    def test_json_serialization(self):
        """Test that all payloads can be serialized to JSON."""
        test_payloads = [
            {"screen": "fast/48"},
            {"screen": "learn/video/902"},
            {"screen": "prayer-set/44"},
            {"screen": "activity", "params": {"activity_type": "announcement"}},
            {"url": "https://example.com"},
        ]

        for payload in test_payloads:
            # Should not raise exception
            json_str = json.dumps(payload)
            # Should be able to parse it back
            parsed = json.loads(json_str)
            self.assertEqual(payload, parsed)


class RouteMapValidationTests(TestCase):
    """
    Validate that the JavaScript route mapping matches frontend expectations.
    """

    def setUp(self):
        """Set up the route mapping as defined in the JavaScript."""
        self.route_map = {
            'fast': 'fast',
            'devotional': 'devotional',
            'prayer': 'prayer',
            'video': 'learn/video',
            'article': 'learn/article',
            'recipe': 'learn/recipe',
            'prayer_set': 'prayer-set',
        }

    def test_learning_resources_have_prefix(self):
        """Verify learning resources have learn/ prefix."""
        learning_resources = ['video', 'article', 'recipe']
        for resource in learning_resources:
            route = self.route_map[resource]
            self.assertTrue(
                route.startswith('learn/'),
                f"{resource} should have 'learn/' prefix, got: {route}"
            )

    def test_prayer_set_uses_hyphen(self):
        """Verify prayer_set maps to prayer-set with hyphen."""
        self.assertEqual(
            self.route_map['prayer_set'],
            'prayer-set',
            "prayer_set should map to 'prayer-set' with hyphen"
        )

    def test_standard_routes_no_prefix(self):
        """Verify standard routes have no prefix."""
        standard_routes = ['fast', 'devotional', 'prayer']
        for route_key in standard_routes:
            route = self.route_map[route_key]
            self.assertFalse(
                '/' in route,
                f"{route_key} should not have slashes: {route}"
            )

    def test_all_routes_lowercase(self):
        """Verify all routes are lowercase."""
        for route_key, route_value in self.route_map.items():
            self.assertEqual(
                route_value,
                route_value.lower(),
                f"Route {route_value} should be lowercase"
            )


class AnnouncementExternalLinkTests(TestCase):
    """
    Test announcement external link functionality.

    Based on the spec:
    - Announcements with external links use activity_type='announcement'
    - data.announcement_url holds the URL
    - App opens URL in platform browser via openExternalLink
    """

    def test_announcement_with_url_in_data(self):
        """Test announcement data structure with URL."""
        announcement_data = {
            "announcement_id": 123,
            "announcement_url": "https://example.com/news",
            "publish_at": "2025-01-01T00:00:00Z",
            "expires_at": None,
        }

        self.assertIn("announcement_url", announcement_data)
        self.assertTrue(announcement_data["announcement_url"].startswith("https://"))

    def test_announcement_activity_feed_payload(self):
        """Test activity feed payload for announcement with URL."""
        payload = {
            "screen": "activity",
            "params": {
                "activity_type": "announcement",
                "target_id": "987"
            }
        }

        # This opens activity feed and finds announcement #987
        # The app then reads data.announcement_url from the feed item
        self.assertEqual(payload["params"]["activity_type"], "announcement")
        self.assertEqual(payload["params"]["target_id"], "987")

    def test_direct_external_url_skips_activity(self):
        """Test direct external URL bypasses activity feed."""
        payload = {"url": "https://example.com/direct"}

        # URL contains :// so notification handler treats it as external
        # Opens directly without going to Activity screen
        self.assertIn("://", payload["url"])
        self.assertNotIn("screen", payload)
        self.assertNotIn("params", payload)
