"""App constants."""
NUMBER_PARTICIPANTS_TO_SHOW_WEB = 6  # number of participant thumbnails to show on fast card on web version
DATE_FORMAT_STRING = "%m/%d/%Y"  # format string for dates (month, day, year)

CATENA_HOME_PAGE_URL = "https://catenabible.com/"
CATENA_ABBREV_FOR_BOOK = {
    # Old Testament
    "Genesis": "gn",
    "Exodus": "ex",
    "Leviticus": "lv",
    "Numbers": "nm",
    "Deuteronomy": "dt",
    "Joshua": "jo",
    "Judges": "jgs",
    "Ruth": "ru",
    "1 Samuel": "1sm",
    "2 Samuel": "2sm",
    "1 Kings": "1kgs",
    "2 Kings": "2kgs",
    "1 Chronicles": "1chr",
    "2 Chronicles": "2chr",
    "Ezra": "ezr",
    "Nehemiah": "neh",
    "Tobit": "tb",
    "Judith": "jdt",
    "Esther": "est",
    "1 Maccabees": "1mc",
    "2 Maccabees": "2mc",
    "Job": "jb",
    "Psalms": "ps",
    "Proverbs": "prv",
    "Ecclesiastes": "eccl",
    "Song of Solomon": "sg",
    "Wisdom of Solomon": "ws",
    "Wisdom": "ws",
    "Sirach": "sir",
    "Isaiah": "is",
    "Jeremiah": "jer",
    "Lamentations": "lam",
    "Epistle of Jeremiah": "eoj",
    "Baruch": "bar",
    "Ezekiel": "ez",
    "Daniel": "dn",
    "Hosea": "hos",
    "Joel": "jl",
    "Amos": "am",
    "Obadiah": "ob",
    "Jonah": "jon",
    "Micah": "mi",
    "Nahum": "na",
    "Habakkuk": "hb",
    "Zephaniah": "zep",
    "Haggai": "hg",
    "Zechariah": "zec",
    "Malachi": "mal",
    # New Testament
    "Matthew": "mt",
    "Mark": "mk",
    "Luke": "lk",
    "John": "jn",
    "Acts": "acts",
    "Acts of the Apostles": "acts",
    "Romans": "rom",
    "St. Paul's Epistle to the Romans": "rom",
    "1 Corinthians": "1cor",
    "St. Paul's First Epistle to the Corinthians": "1cor",
    "2 Corinthians": "2cor",
    "St. Paul's Second Epistle to the Corinthians": "2cor",
    "Galatians": "gal",
    "St. Paul's Epistle to the Galatians": "gal",
    "Ephesians": "eph",
    "St. Paul's Epistle to the Ephesians": "eph",
    "St. Paul's Epistle to the Philippians": "phil",
    "Colossians": "col",
    "St. Paul's Epistle to the Colossians": "col",
    "1 Thessalonians": "1thes",
    "St. Paul's First Epistle to the Thessalonians": "1thes",
    "2 Thessalonians": "2thes",
    "St. Paul's Second Epistle to the Thessalonians": "2thes",
    "1 Timothy": "1tm",
    "St. Paul's First Epistle to Timothy": "1tm",
    "2 Timothy": "2tm",
    "St. Paul's Second Epistle to Timothy": "2tm",
    "Titus": "ti",
    "St. Paul's Epistle to Titus": "ti",
    "Philemon": "phlm",
    "St. Paul's Epistle to Philemon": "phm",
    "Hebrews": "heb",
    "St. Paul's Epistle to the Hebrews": "heb",
    "James": "jas",
    "St. James' Epistle General": "jas",
    "St. James General Epistle": "jas",
    "1 Peter": "1pt",
    "St. Peter's First Epistle General": "1pt",
    "2 Peter": "2pt",
    "St. Peter's Second Epistle General": "2pt",
    "1 John": "1jn",
    "St. John's First Epistle General": "1jn",
    "2 John": "2jn",
    "St. John's Second Epistle General": "2jn",
    "3 John": "3jn",
    "St. John's Third Epistle General": "3jn",
    "Jude": "jude",
    "Revelation": "rv"
}
