# Generated by Django 4.2.11 on 2024-11-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(help_text="Content in Markdown format")),
                (
                    "image",
                    models.ImageField(
                        help_text="Main article image. Recommended size: 1600x1200 pixels (4:3)",
                        upload_to="articles/images/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Articles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "thumbnail",
                    models.ImageField(
                        help_text="Recommended size: 720x1280 pixels (portrait)",
                        upload_to="videos/thumbnails/",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        help_text="Supported formats: MP4, WebM. Portrait orientation (9:16)",
                        upload_to="videos/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Videos",
                "ordering": ["-created_at"],
            },
        ),
    ]
