# Generated by Django 4.2.11 on 2025-02-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('devotional', 'Devotional'), ('tutorial', 'Tutorial')], db_index=True, default='general', max_length=20),
        ),
    ]
