# Generated by Django 4.2.11 on 2025-02-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cached_thumbnail_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='cached_thumbnail_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='cached_thumbnail_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='cached_thumbnail_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
