# Generated by Django 4.2.11 on 2025-02-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resources', '0002_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('devotional', 'Devotional'), ('tutorial', 'Tutorial'), ('morning_prayers', 'Morning Prayers'), ('evening_prayers', 'Evening Prayers')], db_index=True, default='general', max_length=20),
        ),
    ]
