# Generated by Django 4.2.11 on 2025-02-27 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resources', '0003_video_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learning_resources.article')),
                ('time_required', models.CharField(max_length=64, verbose_name='Time required to make recipe')),
                ('serves', models.CharField(max_length=32, verbose_name='Number of servings')),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField(help_text='Content in Markdown format', verbose_name='Instructions')),
            ],
            options={
                'verbose_name_plural': 'Recipes',
                'ordering': ['-created_at'],
            },
            bases=('learning_resources.article',),
        ),
    ]
