# Generated by Django 4.2.11 on 2025-03-03 01:37

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resources', '0003_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=s3direct.fields.S3DirectField(help_text='Supported formats: MP4, WebM. Portrait orientation (9:16). Files up to 20GB.'),
        ),
    ]
