# Generated by Django 4.2.11 on 2025-03-03 13:33

from django.db import migrations, models
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resources', '0004_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Recommended size: 720x1280 pixels (portrait)', null=True, upload_to='videos/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=s3_file_field.fields.S3FileField(help_text='Supported formats: MP4, WebM. Portrait orientation (9:16). Files up to 20MB.', upload_to='videos/'),
        ),
    ]
