# Generated by Django 4.2.11 on 2025-03-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resources', '0004_alter_video_thumbnail_alter_video_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(help_text='Main recipe image. Recommended size: 1600x1200 pixels (4:3)', upload_to='recipes/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cached_thumbnail_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('cached_thumbnail_updated', models.DateTimeField(blank=True, null=True)),
                ('time_required', models.CharField(max_length=64, verbose_name='Time required to make recipe')),
                ('serves', models.CharField(max_length=32, verbose_name='Number of servings')),
                ('ingredients', models.TextField(help_text='Recipe ingredients in Markdown format', verbose_name='Ingredients')),
                ('directions', models.TextField(help_text='Recipe directions in Markdown format', verbose_name='Directions')),
            ],
            options={
                'verbose_name_plural': 'Recipes',
                'ordering': ['-created_at'],
            },
        ),
    ]
