# Generated by Django 4.2.11 on 2025-05-31 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resources', '0005_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(help_text='Language code (e.g., en, am)', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='learning_resources.video')),
            ],
            options={
                'verbose_name_plural': 'Video Translations',
                'ordering': ['-created_at'],
                'unique_together': {('video', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='RecipeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(help_text='Language code (e.g., en, am)', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_required', models.CharField(max_length=64, verbose_name='Time required to make recipe')),
                ('serves', models.CharField(max_length=32, verbose_name='Number of servings')),
                ('ingredients', models.TextField(help_text='Recipe ingredients in Markdown format', verbose_name='Ingredients')),
                ('directions', models.TextField(help_text='Recipe directions in Markdown format', verbose_name='Directions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='learning_resources.recipe')),
            ],
            options={
                'verbose_name_plural': 'Recipe Translations',
                'ordering': ['-created_at'],
                'unique_together': {('recipe', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(help_text='Language code (e.g., en, am)', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Content in Markdown format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='learning_resources.article')),
            ],
            options={
                'verbose_name_plural': 'Article Translations',
                'ordering': ['-created_at'],
                'unique_together': {('article', 'language_code')},
            },
        ),
    ]
