# Generated by Django 4.2.11 on 2025-07-15 20:38

from django.db import migrations, models
import learning_resources.utils
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resources', '0005_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(help_text='Main article image. Recommended size: 1600x1200 pixels (4:3)', upload_to=learning_resources.utils.article_image_upload_path),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Main recipe image. Recommended size: 1600x1200 pixels (4:3)', upload_to=learning_resources.utils.recipe_image_upload_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Recommended size: 720x1280 pixels (portrait)', null=True, upload_to=learning_resources.utils.video_thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=s3_file_field.fields.S3FileField(help_text='Supported formats: MP4, WebM. Portrait orientation (9:16). Files up to 20MB.', upload_to=learning_resources.utils.video_upload_path),
        ),
    ]
