# Generated by Django 4.2.11 on 2025-07-31 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('learning_resources', '0006_alter_article_image_alter_recipe_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='The ID of the object being bookmarked')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the bookmark was created')),
                ('note', models.TextField(blank=True, help_text='Optional note about this bookmark', null=True)),
                ('content_type', models.ForeignKey(help_text='The type of object being bookmarked', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='The user who created this bookmark', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'content_type'], name='learning_re_user_id_0e7fa4_idx'), models.Index(fields=['user', 'created_at'], name='learning_re_user_id_cdd36a_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
