# Generated by Django 4.2.11 on 2025-10-02 03:20

from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resources', '0007_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'body'), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'description', 'time_required', 'serves', 'ingredients', 'directions'), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='video',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'description'), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='video',
            name='language_code',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
