# Generated by Codex on 2026-05-29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changelog",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
