# Generated by Django 4.2.11 on 2024-11-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devicetoken",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
