# Generated by Django 4.2.11 on 2025-04-09 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0026_profile_receive_promotional_emails'),
        ('notifications', '0002_devicetoken_user_alter_devicetoken_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('content_html', models.TextField()),
                ('content_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('all_users', models.BooleanField(default=False, help_text='Send to all users')),
                ('exclude_unsubscribed', models.BooleanField(default=True, help_text='Exclude users who have unsubscribed from promotional emails')),
                ('church_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.church')),
                ('joined_fast', models.ForeignKey(blank=True, help_text='Send to users who joined this fast', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.fast')),
            ],
        ),
    ]
