# Generated by Django 4.2.11 on 2025-04-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_promoemail_emailsubscriptionpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoemail',
            name='specific_emails',
            field=models.TextField(blank=True, help_text='Email addresses to send promotional email to (one address per line); overrides filters if provided', null=True),
        ),
    ]
