# Generated by Django 4.2.11 on 2025-04-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_promoemail_emailsubscriptionpreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSubscriptionPreference',
        ),
    ]
