# Generated by Django 4.2.11 on 2025-06-08 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_promoemail_selected_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoEmailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this image', max_length=200)),
                ('image', models.ImageField(help_text='Upload image to use in promotional emails', upload_to='promo_email_images/')),
                ('description', models.TextField(blank=True, help_text='Optional description of the image content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this image', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Email Image',
                'verbose_name_plural': 'Promo Email Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
