# Generated by Django 4.2.11 on 2025-04-23 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_promoemail_specific_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoemail',
            name='specific_emails',
        ),
        migrations.AddField(
            model_name='promoemail',
            name='selected_users',
            field=models.ManyToManyField(blank=True, help_text='Select specific users to send this email to. Overrides filters if any users are selected.', related_name='selected_for_promo_emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
