# Generated by Django 4.2.11 on 2025-06-20 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial_models'),
        ('notifications', '0004_promoemail_selected_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoemail',
            name='fast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_emails', to='hub.fast'),
        ),
    ]
