# Generated by Django 4.2.11 on 2025-06-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_promoemail_fast'),
        ('notifications', '0005_promoemailimage'),
    ]

    operations = [
    ]
