# Generated by Django 5.2.17 on 2026-09-09 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0064_fastintention_matched_tags_and_more'),
        ('notifications', '0006_merge_0005_promoemail_fast_0005_promoemailimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFastEmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('fast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.fast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'fast'), name='unique_post_fast_email')],
            },
        ),
        migrations.CreateModel(
            name='PostFastEncouragementEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(help_text='Plain text; separate paragraphs with blank lines.')),
                ('fast', models.OneToOneField(blank=True, help_text='Leave blank to customize the default for all other fasts.', null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.fast')),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.Value(1), condition=models.Q(('fast__isnull', True)), name='unique_default_post_fast_email')],
            },
        ),
    ]
